spring:
  profiles:
    include: api, db

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

  datasource:
    username: ${username_}
    password: ${password}
    driver-class-name: ${driver-class-name}
    url: ${url}

  api:
    short-term-key: ${short-term-key}
    short-term-endpoint: ${short-term-endpoint}
    med-term-key: ${med-term-key}
    med-term-land-endpoint: ${med-term-land-endpoint}
    med-term-temp-endpoint: ${med-term-temp-endpoint}
    data-type: ${data-type}


